---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tucuentadeusuario/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - /bin/chown -R tucuentadeusuario:tucuentadeusuario $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
